- packages/design-system/.storybook/preview.js
- packages/design-system/src/foundation/colors/index.ts
- packages/design-system/src/stories/foundation/colors/Colors.stories.tsx
I added a placeholder module and story for Colors in Lunit Design System Foundation.
* I added a `foundation` folder at the same level as `components` folder since we might have some modules that don't have corresponding React components in Foundation. 
* I also added a "Foundation" section in our storybook.
> feat(design-system): added a placeholder module and story for colors

- packages/design-system-icons/src/stories/Introduction.stories.mdx
- Add `s` to `icon`(icon -> icons)
> [design-system-icons] Fix typo in icon installation guide storybook

- packages/design-system/create.logo.mjs
- packages/design-system/src/foundation/logo.index.mustache
- packages/design-system/src/foundation/logo.stories.mustache
logo index 파일이 생성되도록 추가하였습니다. 
생성된 파일 형태
```ts
export { default as LunitChestCT } from "@/foundation/Logo/LunitChestCT";
export { default as LunitChestCTDark } from "@/foundation/Logo/LunitChestCTDark";
export { default as LunitChestCTBasic } from "@/foundation/Logo/LunitChestCTBasic";
export { default as LunitChestCTBasicDark } from "@/foundation/Logo/LunitChestCTBasicDark";
export { default as LunitCXR } from "@/foundation/Logo/LunitCXR";
...
```
> feat(logo): Add logo index file generator

- .github/workflows/chromatic.yml
- packages/design-system/.storybook/Welcome/Welcome.tsx
- packages/design-system/.storybook/branch.js
- packages/design-system/.storybook/main.js
- packages/design-system/build-storybook.log
- packages/design-system/package.json
- yarn.lock
+ add chromatic to deploy Storybook
+ add permalink of published Storybook by branches
Chromatic에서 Branch별 Permalink를 확인할 수 없어서 
Build별 스토리북에 바로가기를 추가했습니다.
+ LDS-43-chromatic Branch의 **Permalink**: https://lds-43-chromatic--62d7d1f2efc8a1e364b5e5e8.chromatic.com
+ LDS-43-chromatic Branch의 **Build 11 Link**: https://62d7d1f2efc8a1e364b5e5e8-knwrzzozic.chromatic.com
> [LDS-43] storybook, chromatic deploy

- packages/design-system-logo/favicon.mjs
- packages/design-system-logo/package.json
install시 npm으로 설치할지 yarn으로 설치할 지 정하지 못한 경우에 나온 에러메시지가  
install 진행중 이라는 메시지가 같이 노출되어 수정되었습니다. 
AS-IS 
Unable to determine package manager type. Please set the options.
Installing @lunit/design-system-logo...
TO-BE
Unable to determine package manager type. Please set the options.
> fix(logo): install error message

- packages/design-system-logo/package.json
> warning @lunit/design-system-logo@1.0.1: Invalid bin entry for "@lunit/design-system-logo" (in "@lunit/design-system-logo").
warning 메시지를 해결하기위해 수정합니다. 
```json
"bin": {
"@lunit/design-system-logo": "./favicon.mjs"
},
```
@나 / 가 원인으로 생각되어 동일하게 실행될 수 있는 `"bin": "./favicon.mjs",` 으로 수정하였습니다. 
@lunit/design-system-logo@1.0.1-beta.1 를 릴리즈하여 확인하였습니다.
> fix(logo): invalid bin entry warning

- README.md
- packages/design-system-icons/.npmignore
- packages/design-system-icons/package.json
- yarn.lock
#50 에서 발견된 모노레포 내에서 이 패키지 참조가 불가능한 문제를 해결합니다.
기존에는 sub-path에 있는 모듈을 import 시 자연스럽게 resolve 할 수 있도록 다음과 같은 방식을 사용했습니다.
1. dist 안에 빌드 결과물인 index와 각 컴포넌트 폴더를 생성
2. package.json을 dist 안으로 이동
3. package.json에서는 같은 dist 폴더 안에 빌드 결과물이 있다고 가정하고 `main`, `types` 필드 등을 설정
그러나 이 방법으로는 이동 전의 package.json에서는 컴포넌트를 참조할 수 없는 문제가 있고, 배포도 번거로웠습니다.
그래서 [exports](https://webpack.kr/guides/package-exports/)와 [typesVersions](https://github.com/andrewbranch/example-subpath-exports-ts-compat)를 이용하여 sub-path에서 모듈을 찾을 수 있도록 설정하였습니다.
> chore(icons): add sub-paths to exports

- packages/design-system/.storybook/main.js
- packages/design-system/.storybook/preview.js
https://github.com/lunit-io/design-system/pull/50#issuecomment-1319531056
위 pr 에서 문제되었던 의존성 이슈 문제 해결을 위해 storybook + emotion theme 설정을 mui trouble shooting guide 에 맞춰 수정했습니다.
-> 공식 문서 참조 : https://mui.com/material-ui/migration/troubleshooting/#storybook-and-emotion
> chore: update emotion config at storybook setting

- packages/design-system/src/components/SelectControl/Toggle/Toggle.styled.ts
- packages/design-system/src/stories/components/SelectControl/Toggle.stories.tsx
기존에는 마우스 클릭, Tab키를 통하여 Focus가 됬음을 알 수 있는 테두리를 볼 수 있었지만.
Tab키를 통해서만 Focus가 되었음을 알 수 있는 테두리가 보이게 변경하였습니다.
> Focus Border update

- packages/design-system/src/components/Chip/Chip.styled.ts
- packages/design-system/src/components/Chip/Chip.tsx
- packages/design-system/src/components/Chip/Chip.types.ts
- packages/design-system/src/components/Chip/consts.ts
- packages/design-system/src/components/Chip/index.ts
- packages/design-system/src/stories/components/Chip/Chip.stories.tsx
- Theme controller 작업이 병합됨에 따라 Chip 스토리북에서 decorator 제거 7930f5e1614b188e681f5c74bab99f2f050bbde4
- 컴포넌트 리팩토링(1): theme을 import하지 않고 sx에서 바로 사용 57b7162adaaf0479b4e619e45362d5996ac72844
- 컴포넌트 리팩토링(2): 반복되던 color token 적용 함수로 빼기 & 불필요하게 전역으로 선언되었던 css 상수를 styled 안으로 이동 9dd4c7924951447760d185c7cf66bf65544df019
- 리팩토링 방향이 옳은지, 과정에서 오류가 생기지는 않았는지 확인해주세요.
- [참고] 현재 DS에서 아래 오류가 발생할 때가 있으나, known issue로 스토리북 7 마이그레이션과 함께 해결될지 지켜볼 예정입니다. 구동에는 문제가 없습니다.
- [피그마 링크](https://www.figma.com/file/BSdRUpEPp7XiJ9YnEqpf6F/Components_%EC%9E%91%EC%97%85%EC%9A%A9?node-id=12893%3A225930&t=5r1jZGNoB2d3ily1-1)
- [JIRA 이슈](https://lunit.atlassian.net/jira/software/projects/DS/boards/31?selectedIssue=DS-9)
- [관련 PR](https://github.com/lunit-io/design-system/pull/79)
> [LDS-9] refactor custom chip component

- packages/design-system/src/stories/components/Chip/Chip.stories.tsx
Nx 마이그레이션 과정에서 발견된 [잘못된 기술 적용](https://github.com/lunit-io/design-system/pull/88#issuecomment-1432805636)을 발견하고 수정합니다.
- 6.4 버전에서 지원하지 않는 conditional controls 제거
- [관련 PR](https://github.com/lunit-io/design-system/pull/86)
별 문제 없으면 바로 머지하겠습니다.
> fix(chip): remove not-working if controls

- packages/design-system/src/components/Chip/Chip.styled.ts
- packages/design-system/src/components/Chip/Chip.tsx
- 컴포넌트 단에서 core.hover 레이어를 입히기로 결정함에 따라 chip에 hover 구현
- Chip의 deleteIcon은 `:before`로 가상 엘리먼트를 구현할 수 없으므로 core.hover 색상을 입힌 deleteIcon을 위에 겹쳐서 구현
- 아래 Develop Backgrounds에 루닛 컬러 시스템의 hover 레이어 구현과 관련된 그간의 논의를 정리해놓았으니 확인 부탁드립니다.
- [피그마 링크 - color](https://www.figma.com/file/yA3cytTNAqhNoXaGxAPrS7/Lunit_Color?node-id=2%3A2&t=smPUUmjhGTAsh8yX-1)
- [피그마 링크 - chip](https://www.figma.com/file/BSdRUpEPp7XiJ9YnEqpf6F/Components_%EC%9E%91%EC%97%85%EC%9A%A9?node-id=12893%3A225930&t=5r1jZGNoB2d3ily1-1)
- [core.hover 컬러 적용과 관련된 JIRA 이슈 코멘트](https://lunit.atlassian.net/browse/DS-2?focusedCommentId=29204)
1. 디자인 상에서의 hover 컬러는 아래와 같이 state layer가 Container와 Contents 사이에 위치하여 표현됩니다.
state layer 방식이 고안된 이유는 light1, light2, dark1, dark2, dark3, dark4에 따라서 달라져야 하는 token 별 hover 색상을 모두 정의하기에는 색상 생성/수정/유지 …
> [LDS-2][LDS-9] add hover effect on chip

- packages/design-system-logo/package.json
package.json에 `main` 설정이 build 파일과 일치하지 않아 이슈가 발생하였습니다. 
Vite로 셋팅된 프로젝트에서만 정확하게 에러를 뿜네요.  
테스트는 `1.0.3-alpha.1` 를 배포하여 테스트 하였습니다. 
**error message**
> [Logo] Fix entry point

- packages/design-system/src/components/Button/Button.styled.ts
- packages/design-system/src/components/Button/utils/getHoverStyle.ts
- packages/design-system/src/stories/components/Button/Kind.stories.tsx
- packages/design-system/src/stories/components/ToggleButton/ToggleButtonKind.stories.tsx
**Button**과 **Toggle Button**에 hover style을 추가하였습니다. 
캡쳐화면인 style book kind별 hover style정의는 로컬에서만 보여지는 이슈가 있습니다. 
Chromatic에선 ghost와 outlined만 스냅샷이 만들어 졌습니다. 😓
> [Button] Add hover style

- packages/design-system/src/components/Chip/Chip.styled.ts
- packages/design-system/src/stories/components/Chip/Chip.stories.tsx
- active 시에 보이던 boxShadow 제거
- 불필요한 type import 제거
- 단순 수정이므로 문제 없으면 바로 머지하겠습니다.
- [피그마 링크 - chip](https://www.figma.com/file/BSdRUpEPp7XiJ9YnEqpf6F/Components_%EC%9E%91%EC%97%85%EC%9A%A9?node-id=12893%3A225930&t=5r1jZGNoB2d3ily1-1)
> [LDS-9] remove unused imports & boxShadow

- packages/design-system/src/components/Button/Button.tsx
- packages/design-system/src/components/Button/Button.types.ts
- packages/design-system/src/components/ToggleButton/ToggleButton.types.ts
- packages/design-system/src/stories/components/Button/BasicButton.stories.tsx
- packages/design-system/src/stories/components/Button/IconButton.stories.tsx
- packages/design-system/src/stories/components/Button/Kind.stories.tsx
- packages/design-system/src/stories/components/ToggleButton/Basic.stories.tsx
- packages/design-system/src/stories/components/ToggleButton/Group.stories.tsx
- packages/design-system/src/stories/components/ToggleButton/ToggleButtonKind.stories.tsx
- packages/design-system/src/stories/components/ToggleButton/WithIcon.stories.tsx
불필요한 hasIconOnly props type 에 대한 코드 및 내용을 삭제합니다.
트리쉐이킹을 위해 아이콘을 가져올 때 subPath 로 접근하여 해당 Icon 만 가져옵니다.
Button, ToggleButton 스토리북 정상 동작하는 것 확인했습니다.
> Remove hasIconOnly props to Button

- packages/design-system/src/components/Toast/Toast.tsx
- packages/design-system/src/components/Toast/Toast.types.ts
- packages/design-system/src/stories/components/Toast/Toast.stories.tsx
지난 주 회의에서 결정되었던 Severity의 옵션에 따라 변경하였습니다.
Default Value를 지우고 normal 옵션을 써야하도록 강제하였습니다.
> Delete default value for severity

- .gitignore
- packages/design-system-logo/.gitignore
- packages/design-system-logo/.npmignore
- packages/design-system-logo/generator.mjs
- packages/design-system-logo/package.json
- packages/design-system-logo/src/logo.stories.mustache
- packages/design-system-logo/webpack.config.js
- tsconfig.json
> #118 에 이어 작업했습니다.
`@lunit/design-system-logo` 패키지 구조를 업데이트합니다. `dist`로 `package.json`을 복사 후 `dist` 안에서 패키지를 배포하는 기존 방식 대신, 프로젝트 루트에서 그대로 배포하는 대신 각 컴포넌트의 경로를 `package.json`의 `exports` 필드에 지정하였습니다(icons와 같은 방식)
이번 변경사항으로 `nextjs-design-system`에서 `@lunit/design-system-logo`를 정상적으로 임포트하여 사용할 수 있게 되었습니다.
> Logo refactor

- packages/design-system/src/components/TextField/TextField.style.ts
- packages/design-system/src/components/TextField/TextField.tsx
- packages/design-system/src/components/TextField/TextField.types.ts
- `TextField` 에서 `size`, `variant` 가 필수값으로 지정된 버그를 수정합니다.
위 수정사항을 통해 `TextField` 는 아무런 값을 넣지 않아도 동작합니다.
- `TextField` 사용 시, `width: 100%` 스타일을 지정해야 적용되는 버그를 수정합니다.
이제 기본적으로 `width: 100%` 스타일이 지정됩니다.
_([이슈 제보 PR](https://github.com/lunit-io/design-system/pull/121))_
> [Fix] TextField wrong props type and style

- packages/design-system/src/components/Button/Button.styled.ts
- packages/design-system/src/components/Button/Button.tsx
- `Button` 에서 default kind 가 `contained` 로 지정되지 않는 이슈를 해결합니다.
- 버그가 발생한 원인은 다음과 같습니다.
- default parameter 를 적용한 부분은 구조분해할당된 kind 였으나,
실제 CustomButton 의 kind props 로 넘겨준 value 는 props.kind 즉 default parameter 가
적용되지 않은 값을 넘겨주었습니다.
이로 인해, Mui Button 의 default value 인 [`text(ghost)`](https://mui.com/material-ui/react-button/#basic-button) 가 적용되어 버그가 발생했습니다.
- 버그 해결 방식은 다음과 같습니다.
- props.kind 의 값이 없을 때 넣어줄 값을 props 로 넘겨줄 때 진행합니다. [bcedd80](https://github.com/lunit-io/design-system/pull/125/commits/bcedd80da71feb75c07789adb0cdc8f796300442)
> [Fix] Button Component default kind Bug Fix

- apps/nextjs-test-system/components/MainBoard.tsx
- apps/nextjs-test-system/components/SidePanel.tsx
- apps/nextjs-test-system/pages/_app.tsx
- packages/design-system/.storybook/preview.js
- packages/design-system/src/components/Alert/Alert.styled.ts
- packages/design-system/src/components/Alert/Alert.utils.ts
- packages/design-system/src/components/Button/Button.styled.ts
- packages/design-system/src/components/Checkbox/Checkbox.tsx
- packages/design-system/src/components/Chip/Chip.styled.ts
- packages/design-system/src/components/Radio/Radio.tsx
- packages/design-system/src/components/TextField/TextField.style.ts
- packages/design-system/src/components/Toast/Toast.styled.ts
- packages/design-system/src/components/Toast/Toast.utils.ts
- packages/design-system/src/components/Toggle/Toggle.styled.ts
- packages/design-system/src/components/ToggleButton/ToggleButton.styled.ts
- packages/design-system/src/foundation/Elevation/index.ts
- packages/design-system/src/foundation/colors/index.ts
- packages/design-system/src/stories/components/Alert/Alert.stories.tsx
- packages/design-system/src/stories/foundation/Typography/TypographyGroup.tsx
- packages/design-system/src/stories/foundation/colors/Colors.stories.tsx
- packages/design-system/src/stories/foundation/colors/Token.inComponent.stories.tsx
- packages/design-system/src/stories/foundation/colors/TokenPaletteTable.tsx
- packages/design-system/src/stories/foundation/colors/styled.ts
[DS-76]
- MUI theme 내 lunit color token 과 lunit global color 의 구조가 mui 기본 palette 와 헷갈리는 이슈
- Lunit 에서 사용하는 컬러의 hierarchy 와 이름을 다음과 같이 수정하여 이용자들이 color token 사용 시 혼동을 막고자 함
```
Global color : theme.palette.lunit =>  theme.palette.lunit_global
Color Token  : theme.palette.token =>  theme.palette.lunit_token
```
- token 이름을 변경함에 따라 token 을 사용하고 있는 코드 수정 진행
<br />
[DS-76]: https://lunit.atlassian.net/browse/DS-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-76] color token hierarchy 수정 + 컴포넌트 내 color token 수정

- packages/design-system/src/components/TextField/TextField.style.ts
[DS-85]
- TextField color token 을 변경합니다.
[DS-85]: https://lunit.atlassian.net/browse/DS-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-85] TextField Placeholder color token 변경

- packages/design-system/src/components/Button/Button.styled.ts
[DS-89](https://lunit.atlassian.net/browse/DS-89?atlOrigin=eyJpIjoiZTBlY2U1MzIxYzk1NDUzZjlmMWQ4NTZhMDgyOTZmNjAiLCJwIjoiaiJ9)
- Button component 의 기본 height 값을 지정합니다.
(Toggle Button 은 기본 Button style 을 공유하므로 따로 수정하지 않아도 적용됩니다.)
[DS-89]: https://lunit.atlassian.net/browse/DS-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-89] Add Button Default Height 

- packages/design-system/src/components/TextField/TextField.style.ts
[DS-92](https://lunit.atlassian.net/browse/DS-92)
- TextField 에 적용된 width 100% 스타일을 삭제합니다.
[DS-92]: https://lunit.atlassian.net/browse/DS-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-92] TextField width 100% 삭제

- packages/design-system/src/foundation/colors/index.ts
Purple 색상 정의는 이미 되어있었으나 `PaletteOption`, `Palette` 타입에 `purple` 항목이 정의되지 않아 해당 부분 수정
- Jira 이슈: https://lunit.atlassian.net/jira/software/projects/DS/boards/31?selectedIssue=DS-97
> [DS-97] Purple color type 추가

- packages/design-system/src/components/Button/Button.styled.ts
- packages/design-system/src/components/Button/Button.tsx
- packages/design-system/src/components/Button/Button.types.ts
- packages/design-system/src/components/Button/utils/getButtonPaddingBySizeAndKind.ts
- packages/design-system/src/components/Button/utils/getIconButtonPaddingBySizeAndKind.ts
- packages/design-system/src/components/Chip/Chip.styled.ts
- packages/design-system/src/components/Chip/Chip.tsx
- packages/design-system/src/components/Chip/Chip.types.ts
[DS-83]
Chip 에 `component` prop 을 추가합니다.
[기존 Generic 방식](https://mui.com/material-ui/guides/composition/#with-typescript)은 타입 추론 이슈가 있어 `OverridableComponent` 을 사용한 방법을 적용합니다.
- [OverridableComponent 를 활용한 component 적용 방식](https://github.com/mui/material-ui/issues/35026#issuecomment-1322630219)
- [OverridableComponent 관련 예제](https://codesandbox.io/s/confident-sun-652mrk?file=/src/App.tsx)
[DS-83]: https://lunit.atlassian.net/browse/DS-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-83] Chip component prop 적용 및 Button component prop 개선

- packages/design-system/src/components/TextField/TextField.tsx
[DS-87]
Single TextField 사용 시, InputProps 가 적용되지 않는 이슈를 해결합니다.
이를 통해 Jira 티켓의 auto complete 레이아웃이 사라지는 이슈도 해결합니다.
해결되는 이유는 다음과 같습니다.
auto complete 레이아웃을 표기하기 위해선 Autocomplete renderInput props 의 parameter 를
TextField component 로 전달해야합니다. 위 parameter 에서 `TextField InputProps Ref` 를 전달해야하는데,
디자인 시스템 TextField 에서 InputProps 를 SingleTextField 로 전달하지 않아 레이아웃을 표기할 수 없는 이슈가 발생합니다.
[DS-92]: https://lunit.atlassian.net/browse/DS-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DS-87]: https://lunit.atlassian.net/browse/DS-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-87] TextField InputProps 미적용 이슈 해결

- packages/design-system/src/components/TextField/TextField.style.ts
- packages/design-system/src/stories/components/TextField/TextFieldMulti.stories.tsx
- packages/design-system/src/stories/components/TextField/TextFieldSingle.stories.tsx
[DS-95]
TextField 에 Error Focus 상태를 추가합니다.
스타일 수정 및 관련하여 story 를 추가했습니다.
[DS-95]: https://lunit.atlassian.net/browse/DS-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-95] add TextField Error Focus status

- packages/design-system/src/components/TextField/TextField.tsx
[DS-82]
TextField 컴포넌트에서 ref prop 사용 시, 에러가 발생하는 이슈를 해결합니다.
`forwardRef` 를 사용하지 않을 경우, ref prop 을 사용할 수 없으며 이로 인해 에러가 발생합니다.
TextField component 에 forwardRef 를 사용하여 위 이슈를 해결합니다.
본 PR 은 [TextField InputProps 미적용 이슈 해결 PR](https://github.com/lunit-io/design-system/pull/135) 머지 이 후 리뷰 부탁드립니다.
[DS-82]: https://lunit.atlassian.net/browse/DS-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-82] TextField ref prop 사용 에러 이슈 해결

- packages/design-system/src/components/Button/Button.tsx
- packages/design-system/src/components/ToggleButton/ToggleButton.tsx
- packages/design-system/src/components/ToggleButton/ToggleButton.types.ts
[DS-113](https://lunit.atlassian.net/browse/DS-113)
기존 Button, ToggleButton 에 forwardRef 가 적용되지 않아 Ref 를 받지 않는 이슈를 해결합니다.
[DS-113]: https://lunit.atlassian.net/browse/DS-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-113] Button, ToggleButton forwardRef 적용

- packages/design-system/src/components/Button/Button.tsx
[DS-100](https://lunit.atlassian.net/browse/DS-100)
기존 Button startIcon 을 활용할 수 없는 문제를 해결합니다.
디자인 시스템에서 start Icon 만 적용되므로, icon 이라는 새로운 prop 을 추가 후 반영했으나
end Icon 은 사용 가능하지만, start Icon 이 적용이 안되는 건 이상하다고 생각하여 다시 살리는 방향으로 수정했습니다.
이미 디자인 시스템을 사용 중인 프로젝트가 있고, icon prop 을 활용하고 있어 icon prop 은 삭제하지 않았습니다.
차후 `deprecated -> icon prop 삭제` 방향으로 생각하고 있는데 이에 대한 의견을 듣고 싶습니다.
[DS-100]: https://lunit.atlassian.net/browse/DS-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-100] Button startIcon prop 활성화

- packages/design-system/src/components/Button/Button.styled.ts
- packages/design-system/src/components/ToggleButton/ToggleButton.styled.ts
- packages/design-system/src/components/ToggleButton/ToggleButton.tsx
[DS-101](https://lunit.atlassian.net/browse/DS-101)
Button 의 svg 사이즈가 20px 로 잘못 지정된 이슈를 해결합니다.
Toggle Button 도 함께 수정됩니다.
- [Figma](https://www.figma.com/file/BSdRUpEPp7XiJ9YnEqpf6F/1.0.0_Components?node-id=13510%3A220759&mode=dev)
[DS-101]: https://lunit.atlassian.net/browse/DS-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-101] Button Svg Size 변경

- packages/design-system/src/foundation/Typography/index.ts
[DS-80]
button 등 일부 엘리먼트에서 font-feature-settings가 적용되지 않는 문제를 수정합니다.
[DS-80]: https://lunit.atlassian.net/browse/DS-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-80] Apply font features to all elements

- apps/nextjs-test-system/components/MainBoard.tsx
- apps/nextjs-test-system/components/SidePanel.tsx
- packages/design-system/src/foundation/Typography/index.ts
- packages/design-system/src/foundation/Typography/tokens.ts
- packages/design-system/src/foundation/colors/index.ts
- packages/design-system/src/foundation/index.ts
[DS-115]
각 Typography 컴포넌트마다 `color`를 지정한 #148 의 방식은 아래 문제가 있었습니다.
- 텍스트 컬러가 상위 스타일을 상속받지 못하기 때문에 사용이 불편함
- Typography 컴포넌트나 그 스타일을 적용하지 않은 일반 텍스트의 경우 `.light1`등 베이스를 지정하더라도 Mui의 기본 컬러를 따라감
이 때문에 각 베이스 클래스에 직접 `color`를 지정하였습니다. 
또한 베이스 클래스가 없는 경우 fallback으로 기본값인 dark1에 해당하는 솔리드 컬러를 지정하였습니다.
제대로 적용되는지 테스트를 위해 테스트시스템에 직접 입력하신 `text_normal` 컬러는 제거하였습니다 @HyejinYang 
[DS-115]: https://lunit.atlassian.net/browse/DS-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-115] Set default color for texts

- apps/nextjs-test-system/components/SidePanel.tsx
- package-lock.json
- packages/design-system/src/components/Button/Button.styled.ts
- packages/design-system/src/components/Button/Button.tsx
- packages/design-system/src/components/Button/Button.types.ts
- packages/design-system/src/components/Chip/Chip.tsx
- packages/design-system/src/components/Chip/Chip.types.ts
- packages/design-system/src/components/TextField/TextField.tsx
- packages/design-system/src/components/TextField/TextField.types.ts
- packages/design-system/src/stories/components/Button/BasicButton.stories.tsx
- packages/design-system/src/stories/components/Button/IconButton.stories.tsx
- packages/design-system/src/stories/components/Button/Kind.stories.tsx
- packages/design-system/src/stories/components/Chip/Chip.stories.tsx
[DS-104]
- chip 컴포넌트에 kind props의 alias로 variant 사용 선적용
- kind의 대체 props로 variant 적용 bd5f69cdcd41287151a66c28cd5aff3727b12f9d
- storybook에 variant 추가 6404ff03b396596e47fd838013333ea6f11cf454
- button 컴포넌트 variant 적용 [4fbbcc9](https://github.com/lunit-io/design-system/pull/150/commits/4fbbcc9cf494bf9ae1c2f821dfb0b4e79692912e)
- button storybook variant 변경 사항 적용 [f9a0f09](https://github.com/lunit-io/design-system/pull/150/commits/f9a0f09312023e59943fe6fd63b3fad95d6f4403)
- 히스토리 기록 차 [슬랙 논의 링크](https://lunit.slack.com/archives/C02FGSSMN7Q/p1701849864038259)를 걸어둡니다.
- Textfield는 현재 변경이 필요치 않은 상황이며, Button, Button Toggle은 본 PR에서 @LTakhyunKim 님이 이어 작업하시기로 하였습니다. 일단 Chip에서 선적용한 형태가 다른 컴포넌트에도 적절할지를 판단 부탁드립니다.
[DS-104]: https://lunit.atlassian.net/browse/DS-104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
> [DS-104] kind props의 alias로 variant 사용

- packages/design-system/src/components/Button/Button.styled.ts
- packages/design-system/src/components/ToggleButton/ToggleButton.styled.ts
[DS-101](https://lunit.atlassian.net/browse/DS-101)
기존 Button SVG 20px 을 적용합니다.
이전 `18px` 로 적용된 부분으로 인해 아이콘 사이즈가 의도보다 작게 보이게 되었습니다.
불필요하게 적용되어 있던 `padding: 1px` 스타일도 삭제 조치했습니다.
위 1px 은 피그마 아이콘 자체에 내장된 것으로 확인하여 삭제했습니다.
- [Design System Button Figma](https://www.figma.com/file/BSdRUpEPp7XiJ9YnEqpf6F/1.0.0_Components?node-id=13510%3A220762&mode=dev)
[DS-101]: https://lunit.atlassian.net/browse/DS-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-101] Button SVG 20px 적용

- packages/design-system-icons/CHANGELOG.md
- packages/design-system-icons/package.json
- packages/design-system-icons/webpack/base.config.js
- packages/design-system-icons/webpack/cjs.config.js
- packages/design-system-icons/webpack/esm.config.js
Fixes #153 
By default, [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals) applies the module's `importType` as `commonjs`. This option has issues with using `require()` in ESM bundles. 
This PR fixes it to use `import` as intended in ESM bundles.
> [DS-119] esm

- packages/design-system/.storybook/preview.js
Jira: [DS-165]
_Elevation_ 스토리북을 포함하여, MUI component 를 사용하고 있는 부분에서 텍스트 컬러가 흰색에 가까워 보이지 않는 현상 발생.
→ 현재 MUI 기본 palette text 색상이 dark1 테마의 색상인데, MUI component 의 기본 배경색은 흰색이라 발생하는 현상
→ Storybook 내 MUI component 의 ~text 기본 색상~ `default palette 컬러`를 `light1` 테마 색상으로 변경하여 가독성 올림
<br />
<br />
[DS-165]: https://lunit.atlassian.net/browse/DS-165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-165] Storybook 의 MUI Component 텍스트 컬러를 위한 theme 업데이트

- packages/design-system/src/components/Checkbox/Checkbox.tsx
- packages/design-system/src/components/Radio/Radio.tsx
[DS-102](https://lunit.atlassian.net/browse/DS-102)
기존에 DataURL을 사용하던 Border는 CSS로 그리고 체크박스 내부 Icon은 SVG로 변경하였습니다.
[DS-102]: https://lunit.atlassian.net/browse/DS-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-102] Remove DataURL from checkbox and radiobox

- packages/design-system/src/stories/components/Chip/Chip.stories.tsx
- packages/design-system/src/stories/components/Chip/ChipDocs.mdx
Jira: [DS-158](https://lunit.atlassian.net/jira/software/projects/DS/boards/31?selectedIssue=DS-158)
Design System Chip에 대한 문서를 작성합니다.
참고: [Storybook 문서 양식](https://lunit.atlassian.net/wiki/spaces/~420757902/pages/3209625692)
- Basic과 ContainedWithDeleteAndThumbnail 스토리를 추가하는 등 기존 스토리북 추가
- Chip docs mdx 추가
되도록 기존에 머지된 Button 스토리 양식을 따르려 했지만, 다소 어색한 표현이 있는 부분은 조금 더 이해가 쉽도록 고쳤으니 참고 부탁드립니다.  
[DS-158]: https://lunit.atlassian.net/browse/DS-158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-158] Chip documentation

- packages/design-system/src/stories/foundation/colors/ColorSystem.tsx
- packages/design-system/src/stories/foundation/colors/Docs.mdx
JIRA : [DS-155]
- Color System & Token 을 설명하는 Storybook Docs 추가
- 읽는 사람이 이해가 편하도록 한글로 작성. 영문 버전이 필요하면 추후 작업하겠습니다.
- 예제는 추후 더 추가할 예정
[DS-155]: https://lunit.atlassian.net/browse/DS-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-155] Color System Docs mdx 추가

- packages/design-system/src/stories/components/ToggleButton/Basic.stories.tsx
- packages/design-system/src/stories/components/ToggleButton/ToggleButtonDocs.mdx
- packages/design-system/src/stories/components/ToggleButton/ToggleButtonKind.stories.tsx
- packages/design-system/src/stories/components/ToggleButton/WithIcon.stories.tsx
Jira: [DS-164](https://lunit.atlassian.net/browse/DS-164)
Design System ToggleButton 에 대한 문서를 작성합니다.
최신 버전 Figma 에선 outlined kind 에 대한 secondary color 를 지원하는 것으로 표기되어 있으나,
이는 코드에 반영되지 않아, 구 버전 Figma 를 추가해두었습니다. 구 버전에선 위 스펙을 지원하지 않고 있고,
구현 역시 구버전에 맞춰져 있다는 점 참고 부탁드립니다.
[DS-164]: https://lunit.atlassian.net/browse/DS-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-164] ToggleButton documentation

- packages/design-system/src/stories/foundation/colors/ColorSystem.tsx
- packages/design-system/src/stories/foundation/colors/Docs.mdx
jira : [ds-188]
- 한글로 쓰여있던 Color Storybook 문서에 영어 번역을 추가
- 어색한 부분이 없는지 확인 부탁드립니다.
> [DS-188] Color storybook 문서에 영어 번역 추가

- packages/design-system/src/components/Dialog/Dialog.styled.ts
- packages/design-system/src/components/Dialog/Dialog.tsx
- packages/design-system/src/components/Dialog/components/DialogAction.tsx
[DS-13](https://lunit.atlassian.net/jira/software/projects/DS/boards/31?selectedIssue=DS-13)
- Dialog 디자인 검수를 받아 스타일 수정을 진행했습니다.
- 주요 변경점: css로 box-shadow를 지정해주는 방식이 아닌, [클래스를 통해 elevation2를 불러오는 방식](c8ec3ad872654f97f3772bf2e84ab036de7aeda3)을 이용했습니다. (루닛 디자인 시스템의 elevation은 토큰이 아닌 클래스로 사용 가능합니다!)
[DS-13]: https://lunit.atlassian.net/browse/DS-13?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-13] Dialog 디자인 검수 & 스타일 수정

- packages/design-system/src/components/Dialog/Dialog.tsx
- packages/design-system/src/stories/components/Dialog/DialogDocs.mdx
- Dialog 문서 추가
- [DS-187](https://lunit.atlassian.net/jira/software/projects/DS/boards/31?selectedIssue=DS-187)
- Dialog는 다른 문서와 달리 Canvas에서 확인이 불가능해 데모를 추가하지 않았습니다.
[DS-187]: https://lunit.atlassian.net/browse/DS-187?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-187]: add Dialog documentation

- packages/design-system/src/components/TextField/TextField.style.ts
[DS-197](https://lunit.atlassian.net/browse/DS-197)
- TextField padding style 을 지정할 때 불필요한 } 가 하나 더 들어간 이슈를 해결합니다.
[DS-197]: https://lunit.atlassian.net/browse/DS-197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [DS-197] TextField padding style } 오타 수정
